### ISSUE TITLE
error when using NOS=5

### ISSUE THREAD

**Issue by Althalis** [DorresteinLaboratory/Kendrick_Mass_Filter#3]
Hi, 

When I run with NOS 5:
![billede](https://user-images.githubusercontent.com/5079495/61954855-1ace0d00-afba-11e9-8b10-b16dc4886497.png)

At line 17, I'm stuck with an error.
![billede](https://user-images.githubusercontent.com/5079495/61954952-4fda5f80-afba-11e9-9e92-61d947084ac9.png)

(The usual NOS 2 works fine)

Thanks for your help again.
best
Julie

**Comment by rsilvabioinfo** [comment]
Hi Julie
With this information is hard to figure out what is happening.

The error is saying that cbind command can not bind the columns of two
matrices of different dimensions. This can be because the output of
'Kendrick.mass.filter' is wrong or empty or there is some other mistake
upstream. A good idea to narrow down the problem would be to break down the
cell '17'. If in your jupyter notebook you create a cell before that, and
execute 'dim' and 'head' functions on the matrices you are trying to
combine maybe you will find the source ot the error.

A useful resource is also some tips to ask a coding question
https://stackoverflow.com/help/how-to-ask

If this filtering is what you need, would be nice if you created a git
repository yourself with a new notebook with the code you executed and the
dataset where you had the problem. With that, we would be able to reproduce
the problem and find exactly what happened.
Cheers,
Ricardo

Em sex, 26 de jul de 2019 às 11:09, Julie Courraud <notifications@github.com>
escreveu:
